In [91]:
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [5]:
df =pd.read_csv('/Users/aadrijupadya/Downloads/archive/US_counties_COVID19_health_weather_data.csv')

In [16]:
df2 = df[['date', 'county', 'state', 'lat', 'lon', 'mean_temp', 'min_temp', 'max_temp', 'dewpoint', 'precipitation', 'rain', 'sea_level_pressure', 'visibility', 'wind_speed', 'max_wind_speed', 'wind_gust', 'precipitation', 'precip_flag', 'fog', 'snow', 'hail', 'thunder', 'tornado']]

In [15]:
for i in df.columns:
    print(i)

date
county
state
fips
stay_at_home_announced
stay_at_home_effective
lat
lon
total_population
area_sqmi
population_density_per_sqmi
num_deaths
years_of_potential_life_lost_rate
percent_fair_or_poor_health
average_number_of_physically_unhealthy_days
average_number_of_mentally_unhealthy_days
percent_low_birthweight
percent_smokers
percent_adults_with_obesity
food_environment_index
percent_physically_inactive
percent_with_access_to_exercise_opportunities
percent_excessive_drinking
num_alcohol_impaired_driving_deaths
num_driving_deaths
percent_driving_deaths_with_alcohol_involvement
num_chlamydia_cases
chlamydia_rate
teen_birth_rate
num_uninsured
percent_uninsured
num_primary_care_physicians
primary_care_physicians_rate
num_dentists
dentist_rate
num_mental_health_providers
mental_health_provider_rate
preventable_hospitalization_rate
percent_with_annual_mammogram
percent_vaccinated
high_school_graduation_rate
num_some_college
population
percent_some_college
num_unemployed_CHR
labor_force
pe

In [17]:
df2

date      county       state        lat         lon  mean_temp  \
0       2020-01-21   Snohomish  Washington  48.047489 -121.697307       44.1   
1       2020-01-22   Snohomish  Washington  48.047489 -121.697307       44.8   
2       2020-01-23   Snohomish  Washington  48.047489 -121.697307       49.9   
3       2020-01-24        Cook    Illinois  41.840039  -87.816716       36.1   
4       2020-01-24   Snohomish  Washington  48.047489 -121.697307       51.5   
...            ...         ...         ...        ...         ...        ...   
790326  2020-12-04  Sweetwater     Wyoming  41.659538 -108.879567       21.1   
790327  2020-12-04       Teton     Wyoming  43.934776 -110.589759        2.4   
790328  2020-12-04       Uinta     Wyoming  41.287648 -110.547639       25.2   
790329  2020-12-04    Washakie     Wyoming  43.904970 -107.682819       17.9   
790330  2020-12-04      Weston     Wyoming  43.840417 -104.567663       36.7   

        min_temp  max_temp  dewpoint  precipitation  ...  wind_speed  \
0           37.0      50.0      40.3           0.00  ...         8.3   
1           37.9      48.0      40.3           0.29  ...        13.2   
2           42.8      54.0      47.3           0.54  ...        12.0   
3           34.0      39.0      34.7           0.16  ...         4.8   
4           48.0      54.0      46.6           0.32  ...        13.0   
...          ...       ...       ...            ...  ...         ...   
790326      19.0      23.0       3.2           0.00  ...         5.2   
790327      -3.3      17.8       NaN           0.00  ...         NaN   
790328      21.0      30.9       4.0           0.00  ...         3.7   
790329      14.0      25.0       7.6           0.00  ...         1.7   
790330      35.2      40.3       NaN           0.00  ...         NaN   

        max_wind_speed  wind_gust  precipitation  precip_flag  fog  snow hail  \
0                 19.0       28.0           0.00            G  0.0   0.0  0.0   
1                 21.0       26.0           0.29            G  0.0   0.0  0.0   
2                 20.0       26.0           0.54            G  0.0   0.0  0.0   
3                  9.9        NaN           0.16            G  1.0   1.0  0.0   
4                 22.0       28.0           0.32            G  0.0   0.0  0.0   
...                ...        ...            ...          ...  ...   ...  ...   
790326             7.0        NaN           0.00            I  0.0   0.0  0.0   
790327             NaN        NaN           0.00            I  0.0   0.0  0.0   
790328             8.9        NaN           0.00            I  0.0   0.0  0.0   
790329             4.1        NaN           0.00            I  0.0   0.0  0.0   
790330             NaN        NaN           0.00            I  0.0   0.0  0.0   

        thunder  tornado  
0           0.0      0.0  
1           0.0      0.0  
2           0.0      0.0  
3           0.0      0.0  
4           0.0      0.0  
...         ...      ...  
790326      0.0      0.0  
790327      0.0      0.0  
790328      0.0      0.0  
790329      0.0      0.0  
790330      0.0      0.0  

[790331 rows x 23 columns]

In [10]:
for i in df.columns:
    print(i)

date
county
state
fips
stay_at_home_announced
stay_at_home_effective
lat
lon
total_population
area_sqmi
population_density_per_sqmi
num_deaths
years_of_potential_life_lost_rate
percent_fair_or_poor_health
average_number_of_physically_unhealthy_days
average_number_of_mentally_unhealthy_days
percent_low_birthweight
percent_smokers
percent_adults_with_obesity
food_environment_index
percent_physically_inactive
percent_with_access_to_exercise_opportunities
percent_excessive_drinking
num_alcohol_impaired_driving_deaths
num_driving_deaths
percent_driving_deaths_with_alcohol_involvement
num_chlamydia_cases
chlamydia_rate
teen_birth_rate
num_uninsured
percent_uninsured
num_primary_care_physicians
primary_care_physicians_rate
num_dentists
dentist_rate
num_mental_health_providers
mental_health_provider_rate
preventable_hospitalization_rate
percent_with_annual_mammogram
percent_vaccinated
high_school_graduation_rate
num_some_college
population
percent_some_college
num_unemployed_CHR
labor_force
pe

In [18]:
a = a[a['Element'] == 'Gross per capita Production Index Number (2014-2016 = 100)']

In [19]:
a

Domain Code              Domain  Area Code (FAO)  \
60           QI  Production Indices              231   
61           QI  Production Indices              231   
62           QI  Production Indices              231   
63           QI  Production Indices              231   
64           QI  Production Indices              231   
65           QI  Production Indices              231   
66           QI  Production Indices              231   
67           QI  Production Indices              231   
68           QI  Production Indices              231   
69           QI  Production Indices              231   
70           QI  Production Indices              231   
71           QI  Production Indices              231   
72           QI  Production Indices              231   
73           QI  Production Indices              231   
74           QI  Production Indices              231   
75           QI  Production Indices              231   
76           QI  Production Indices              231   
77           QI  Production Indices              231   
78           QI  Production Indices              231   
79           QI  Production Indices              231   
80           QI  Production Indices              231   
81           QI  Production Indices              231   
82           QI  Production Indices              231   
83           QI  Production Indices              231   
84           QI  Production Indices              231   
85           QI  Production Indices              231   
86           QI  Production Indices              231   
87           QI  Production Indices              231   
88           QI  Production Indices              231   
89           QI  Production Indices              231   
90           QI  Production Indices              231   
91           QI  Production Indices              231   
92           QI  Production Indices              231   
93           QI  Production Indices              231   
94           QI  Production Indices              231   
95           QI  Production Indices              231   
96           QI  Production Indices              231   
97           QI  Production Indices              231   
98           QI  Production Indices              231   
99           QI  Production Indices              231   
100          QI  Production Indices              231   
101          QI  Production Indices              231   
102          QI  Production Indices              231   
103          QI  Production Indices              231   
104          QI  Production Indices              231   
105          QI  Production Indices              231   
106          QI  Production Indices              231   
107          QI  Production Indices              231   
108          QI  Production Indices              231   
109          QI  Production Indices              231   
110          QI  Production Indices              231   
111          QI  Production Indices              231   
112          QI  Production Indices              231   
113          QI  Production Indices              231   
114          QI  Production Indices              231   
115          QI  Production Indices              231   
116          QI  Production Indices              231   
117          QI  Production Indices              231   
118          QI  Production Indices              231   
119          QI  Production Indices              231   

                         Area  Element Code  \
60   United States of America           434   
61   United States of America           434   
62   United States of America           434   
63   United States of America           434   
64   United States of America           434   
65   United States of America           434   
66   United States of America           434   
67   United States of America           434   
68   United States of America           434   
69   United States of America           434   
70   United States of America           434   
71   United States of A

In [13]:
a

Empty DataFrame
Columns: [Domain Code, Domain, Area Code (FAO), Area, Element Code, Element, Item Code (FAO), Item, Year Code, Year, Unit, Value, Flag, Flag Description]
Index: []

In [8]:
df['Item'].value_counts()

Almonds, with shell            120
Peas, dry                      120
Soybeans                       120
Sorghum                        120
Seed cotton                    120
                              ... 
Chick peas                      60
Meat indigenous, goat           56
Fruit, citrus nes               48
Pumpkins, squash and gourds     42
Vegetables, leguminous nes      34
Name: Item, Length: 115, dtype: int64

In [4]:
df

Domain Code              Domain  Area Code (FAO)  \
0              QI  Production Indices              231   
1              QI  Production Indices              231   
2              QI  Production Indices              231   
3              QI  Production Indices              231   
4              QI  Production Indices              231   
...           ...                 ...              ...   
13107          QI  Production Indices              231   
13108          QI  Production Indices              231   
13109          QI  Production Indices              231   
13110          QI  Production Indices              231   
13111          QI  Production Indices              231   

                           Area  Element Code  \
0      United States of America           432   
1      United States of America           432   
2      United States of America           432   
3      United States of America           432   
4      United States of America           432   
...                         ...           ...   
13107  United States of America           434   
13108  United States of America           434   
13109  United States of America           434   
13110  United States of America           434   
13111  United States of America           434   

                                                 Element  Item Code (FAO)  \
0        Gross Production Index Number (2014-2016 = 100)              221   
1        Gross Production Index Number (2014-2016 = 100)              221   
2        Gross Production Index Number (2014-2016 = 100)              221   
3        Gross Production Index Number (2014-2016 = 100)              221   
4        Gross Production Index Number (2014-2016 = 100)              221   
...                                                  ...              ...   
13107  Gross per capita Production Index Number (2014...             1739   
13108  Gross per capita Production Index Number (2014...             1739   
13109  Gross per capita Production Index Number (2014...             1739   
13110  Gross per capita Production Index Number (2014...             1739   
13111  Gross per capita Production Index Number (2014...             1739   

                               Item  Year Code  Year   Unit  Value Flag  \
0               Almonds, with shell       1961  1961  index   3.93   Fc   
1               Almonds, with shell       1962  1962  index   2.84   Fc   
2               Almonds, with shell       1963  1963  index   3.53   Fc   
3               Almonds, with shell       1964  1964  index   4.44   Fc   
4               Almonds, with shell       1965  1965  index   4.31   Fc   
...                             ...        ...   ...    ...    ...  ...   
13107  Vegetables and Fruit Primary       2016  2016  index  97.98   Fc   
13108  Vegetables and Fruit Primary       2017  2017  index  92.32   Fc   
13109  Vegetables and Fruit Primary       2018  2018  index  89.10   Fc   
13110  Vegetables and Fruit Primary       2019  2019  index  89.50   Fc   
13111  Vegetables and Fruit Primary       2020  2020  index  85.66   Fc   

      Flag Description  
0      Calculated data  
1      Calculated data  
2      Calculated data  
3      Calculated data  
4      Calculated data  
...                ...  
13107  Calculated data  
13108  Calculated data  
13109  Calculated data  
13110  Calculated data  
13111  Calculated data  

[13112 rows x 14 columns]

In [65]:
crop_df = pd.read_csv('/Users/aadrijupadya/Downloads/county_production.csv')

In [68]:
crop_df.iloc[i]['Data Item']

'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE'

In [69]:
crop_df

Program  Year Period  Week Ending Geo Level       State  State ANSI  \
0     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
1     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
2     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
3     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
4     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
...      ...   ...    ...          ...       ...         ...         ...   
8709  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8710  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8711  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8712  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8713  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   

            Ag District  Ag District Code                     County  ...  \
0         CENTRAL COAST                40               CONTRA COSTA  ...   
1         CENTRAL COAST                40               CONTRA COSTA  ...   
2     SACRAMENTO VALLEY                50                      BUTTE  ...   
3     SACRAMENTO VALLEY                50                      BUTTE  ...   
4     SACRAMENTO VALLEY                50                     COLUSA  ...   
...                 ...               ...                        ...  ...   
8709       WEST CENTRAL                40  OTHER (COMBINED) COUNTIES  ...   
8710       WEST CENTRAL                40                   ST CROIX  ...   
8711       WEST CENTRAL                40                   ST CROIX  ...   
8712       WEST CENTRAL                40                   ST CROIX  ...   
8713       WEST CENTRAL                40                   ST CROIX  ...   

      Zip Code  Region  watershed_code  Watershed   Commodity  \
0          NaN     NaN               0        NaN    TOMATOES   
1          NaN     NaN               0        NaN    TOMATOES   
2          NaN     NaN               0        NaN    TOMATOES   
3          NaN     NaN               0        NaN    TOMATOES   
4          NaN     NaN               0        NaN    TOMATOES   
...        ...     ...             ...        ...         ...   
8709       NaN     NaN               0        NaN  SWEET CORN   
8710       NaN     NaN               0        NaN       BEANS   
8711       NaN     NaN               0        NaN       BEANS   
8712       NaN     NaN               0        NaN  SWEET CORN   
8713       NaN     NaN               0        NaN  SWEET CORN   

                                              Data Item Domain  \
0     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
1     TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - ...  TOTAL   
2     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
3     TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - ...  TOTAL   
4     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
...                                                 ...    ...   
8709  SWEET CORN, PROCESSING - YIELD, MEASURED IN TO...  TOTAL   
8710  BEANS, SNAP, PROCESSING - PRODUCTION, MEASURED...  TOTAL   
8711  BEANS, SNAP, PROCESSING - YIELD, MEASURED IN T...  TOTAL   
8712  SWEET CORN, PROCESSING - PRODUCTION, MEASURED ...  TOTAL   
8713  SWEET CORN, PROCESSING - YIELD, MEASURED IN TO...  TOTAL   

     Domain Category    Value CV (%)  
0      NOT SPECIFIED    64.69    NaN  
1      NOT SPECIFIED  168,200    NaN  
2      NOT SPECIFIED       26    NaN  
3      NOT SPECIFIED   18,200    NaN  
4      NOT SPECIFIED    49.46    NaN  
...              ...      ...    ...  
8709   NOT SPECIFIED      4.9    NaN  
8710   NOT SPECIFIED   10,020    NaN  
8711   NOT SPECIFIED      4.6    NaN  
8712   NOT SPECIFIED    9,500    NaN  
8713   NOT SPECIFIED      5.6    NaN  

[8714 rows x 21 columns]

In [70]:
nums = crop_df.values

In [75]:
nums[8]

array(['SURVEY', 2021, 'YEAR', nan, 'COUNTY', 'CALIFORNIA', 6,
       'SACRAMENTO VALLEY', 50, 'SACRAMENTO', 67.0, nan, nan, 0, nan,
       'TOMATOES',
       'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE',
       'TOTAL', 'NOT SPECIFIED', '36.42', nan], dtype=object)

In [90]:
crop_df

Program  Year Period  Week Ending Geo Level       State  State ANSI  \
0     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
1     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
2     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
3     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
4     SURVEY  2021   YEAR          NaN    COUNTY  CALIFORNIA           6   
...      ...   ...    ...          ...       ...         ...         ...   
8709  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8710  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8711  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8712  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   
8713  SURVEY  2000   YEAR          NaN    COUNTY   WISCONSIN          55   

            Ag District  Ag District Code                     County  ...  \
0         CENTRAL COAST                40               CONTRA COSTA  ...   
1         CENTRAL COAST                40               CONTRA COSTA  ...   
2     SACRAMENTO VALLEY                50                      BUTTE  ...   
3     SACRAMENTO VALLEY                50                      BUTTE  ...   
4     SACRAMENTO VALLEY                50                     COLUSA  ...   
...                 ...               ...                        ...  ...   
8709       WEST CENTRAL                40  OTHER (COMBINED) COUNTIES  ...   
8710       WEST CENTRAL                40                   ST CROIX  ...   
8711       WEST CENTRAL                40                   ST CROIX  ...   
8712       WEST CENTRAL                40                   ST CROIX  ...   
8713       WEST CENTRAL                40                   ST CROIX  ...   

      Zip Code  Region  watershed_code  Watershed   Commodity  \
0          NaN     NaN               0        NaN    TOMATOES   
1          NaN     NaN               0        NaN    TOMATOES   
2          NaN     NaN               0        NaN    TOMATOES   
3          NaN     NaN               0        NaN    TOMATOES   
4          NaN     NaN               0        NaN    TOMATOES   
...        ...     ...             ...        ...         ...   
8709       NaN     NaN               0        NaN  SWEET CORN   
8710       NaN     NaN               0        NaN       BEANS   
8711       NaN     NaN               0        NaN       BEANS   
8712       NaN     NaN               0        NaN  SWEET CORN   
8713       NaN     NaN               0        NaN  SWEET CORN   

                                              Data Item Domain  \
0     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
1     TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - ...  TOTAL   
2     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
3     TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - ...  TOTAL   
4     TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEA...  TOTAL   
...                                                 ...    ...   
8709  SWEET CORN, PROCESSING - YIELD, MEASURED IN TO...  TOTAL   
8710  BEANS, SNAP, PROCESSING - PRODUCTION, MEASURED...  TOTAL   
8711  BEANS, SNAP, PROCESSING - YIELD, MEASURED IN T...  TOTAL   
8712  SWEET CORN, PROCESSING - PRODUCTION, MEASURED ...  TOTAL   
8713  SWEET CORN, PROCESSING - YIELD, MEASURED IN TO...  TOTAL   

     Domain Category    Value CV (%)  
0      NOT SPECIFIED    64.69    NaN  
1      NOT SPECIFIED  168,200    NaN  
2      NOT SPECIFIED       26    NaN  
3      NOT SPECIFIED   18,200    NaN  
4      NOT SPECIFIED    49.46    NaN  
...              ...      ...    ...  
8709   NOT SPECIFIED      4.9    NaN  
8710   NOT SPECIFIED   10,020    NaN  
8711   NOT SPECIFIED      4.6    NaN  
8712   NOT SPECIFIED    9,500    NaN  
8713   NOT SPECIFIED      5.6    NaN  

[8714 rows x 21 columns]

In [184]:
x = nums[:,(9,16)]
y = nums[:, 19]

In [185]:
x

array([['CONTRA COSTA',
        'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ['CONTRA COSTA',
        'TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - PRODUCTION, MEASURED IN TONS'],
       ['BUTTE',
        'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ...,
       ['ST CROIX',
        'BEANS, SNAP, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ['ST CROIX',
        'SWEET CORN, PROCESSING - PRODUCTION, MEASURED IN TONS'],
       ['ST CROIX',
        'SWEET CORN, PROCESSING - YIELD, MEASURED IN TONS / ACRE']],
      dtype=object)

In [182]:
label_encoded_x

array([ 47,  74, 326, ..., 359, 309, 319])

In [183]:
x

array([['CALIFORNIA', 'CONTRA COSTA',
        'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ['CALIFORNIA', 'CONTRA COSTA',
        'TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - PRODUCTION, MEASURED IN TONS'],
       ['CALIFORNIA', 'BUTTE',
        'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ...,
       ['WISCONSIN', 'ST CROIX',
        'BEANS, SNAP, PROCESSING - YIELD, MEASURED IN TONS / ACRE'],
       ['WISCONSIN', 'ST CROIX',
        'SWEET CORN, PROCESSING - PRODUCTION, MEASURED IN TONS'],
       ['WISCONSIN', 'ST CROIX',
        'SWEET CORN, PROCESSING - YIELD, MEASURED IN TONS / ACRE']],
      dtype=object)

In [ ]:
{'state'}

In [89]:
y

array(['64.69', '168,200', '26', ..., '4.6', '9,500', '5.6'], dtype=object)

In [154]:
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(x)
label_encoded_x = label_encoder.transform(x)

ValueError: y should be a 1d array, got an array of shape (8714, 3) instead.

In [186]:
test = x.reshape((len(x)*2,1))

In [187]:
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(test)
label_encoded_x = label_encoder.transform(test)

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [188]:
b = label_encoded_x.reshape((8714,2))

In [189]:
b

array([[ 70, 308],
       [ 70, 309],
       [ 44, 308],
       ...,
       [291,  19],
       [291, 300],
       [291, 301]])

In [190]:
from numpy import loadtxt
import xgboost
from xgboost import *
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn import model_selection
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from xgboost import XGBRegressor

In [31]:
crop_df.columns

Index(['Program', 'Year', 'Period', 'Week Ending', 'Geo Level', 'State',
       'State ANSI', 'Ag District', 'Ag District Code', 'County',
       'County ANSI', 'Zip Code', 'Region', 'watershed_code', 'Watershed',
       'Commodity', 'Data Item', 'Domain', 'Domain Category', 'Value',
       'CV (%)'],
      dtype='object')

In [122]:
y = np.array(y)

In [132]:
new_y = []
for i in y:
    list1 = []
    for a in i:
        a = a.replace(',', '')
        list1.append(a)
    new_y.append(list1)

In [134]:
new_y = np.array(new_y)

In [135]:
new_y = [float(i) for i in new_y]

In [138]:
new_y = [[i] for i in new_y]

In [140]:
new_y = np.array(new_y)

In [191]:
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = model_selection.train_test_split(b, new_y, test_size=test_size, random_state=seed)

In [293]:
model = XGBRegressor(seed=20,objective='count:poisson')
# cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
# scores = cross_val_score(model, X_train, y_train, scoring='neg_root_mean_squared_error', cv=cv, n_jobs=-1)


In [296]:
params = { 'max_depth': [3, 5, 6, 10, 15, 20],
           'learning_rate': [0.01, 0.1, 0.2, 0.3],
           'subsample': np.arange(0.5, 1.0, 0.1),
           'colsample_bytree': np.arange(0.4, 1.0, 0.1),
           'colsample_bylevel': np.arange(0.4, 1.0, 0.1),
           'n_estimators': [100, 500, 1000] 
         objective='count'}
clf = RandomizedSearchCV(estimator=model, param_distributions=params, scoring='neg_root_mean_squared_error', n_iter=25,verbose=1)

In [297]:
clf.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


RandomizedSearchCV(estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=False,
                                          eval_metric=None, gamma=None,
                                          gpu_id=None, grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints=None,
                                          learning_rate=None, max_bin=None,
                                          max_ca...
                                          predictor=None, random_state=None,
                                          reg_alpha=None, ...),
                   n_iter=25,
                   param_distributions={'colsample_bylevel': array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                                        'colsample_bytree': array([0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
                                        'learning_rate': [0.01, 0.1, 0.2, 0.3],
                                        'max_depth': [3, 5, 6, 10, 15, 20],
                                        'n_estimators': [100, 500, 1000],
                                        'subsample': array([0.5, 0.6, 0.7, 0.8, 0.9])},
                   scoring='neg_root_mean_squared_error', verbose=1)

In [300]:
print("Best parameters:", clf.best_params_)
print("Lowest RMSE: ", (-clf.best_score_)**(1/2.0))

Best parameters: {'subsample': 0.7999999999999999, 'n_estimators': 1000, 'max_depth': 6, 'learning_rate': 0.1, 'colsample_bytree': 0.6, 'colsample_bylevel': 0.8999999999999999}
Lowest RMSE:  2228.50739979034


In [329]:
model = XGBRegressor(objective='count:poisson', subsample=0.8, n_estimators=1000, max_depth=6, learning_rate=0.1, colsample_bytree=0.6, colsample_bylevel=0.9)


In [330]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [331]:
y_pred

array([1.5337943e+00, 1.5085678e+06, 6.8342438e+00, ..., 8.4730788e+05,
       3.5586803e+05, 4.6174469e+02], dtype=float32)

In [332]:
y_test

array([[0.0000e+00],
       [3.8426e+07],
       [0.0000e+00],
       ...,
       [3.9000e+04],
       [4.2000e+05],
       [4.8900e+02]])

In [318]:
zeroes = []
for i in range(len(y_test)):
    if y_test[i] == 0.0:
        zeroes.append(i)
        

In [327]:
y_pred[10]

-158377.78

In [328]:
y_test[10]

array([5.5])

In [313]:
y_test[200]

array([2705000.])

In [321]:
y_pred[2743]

692571.44

In [270]:
yhat = model.predict(X_test)


In [271]:
yhat

array([1.09108046e-01, 1.44285125e+06, 6.18627167e+00, ...,
       9.35847188e+05, 3.54204562e+05, 4.85183624e+02], dtype=float32)

In [275]:
y_test[0]

array([0.])

In [274]:
yhat[0]

0.109108046

In [199]:
X_test ==

array([[211, 223],
       [211, 242],
       [130,   9],
       ...,
       [ 73, 242],
       [  0, 242],
       [136, 243]])

In [213]:
county_dict = {}


In [202]:
b

array([[ 70, 308],
       [ 70, 309],
       [ 44, 308],
       ...,
       [291,  19],
       [291, 300],
       [291, 301]])

In [214]:
item_dict = {}

In [215]:
for i in range(0,len(x)):
    county_dict[b[i][0]] = x[i][0]
    item_dict[b[i][1]] = x[i][1]
        
        
    

In [276]:
len(county_dict)

315

In [217]:
item_dict

{308: 'TOMATOES, IN THE OPEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE',
 309: 'TOMATOES, IN THE OPEN, PROCESSING, UTILIZED - PRODUCTION, MEASURED IN TONS',
 230: 'PECANS, UTILIZED, IN SHELL - PRODUCTION, MEASURED IN LB',
 231: 'PECANS, UTILIZED, IN SHELL - YIELD, MEASURED IN LB / ACRE',
 234: 'PEPPERS, CHILE - PRODUCTION, MEASURED IN CWT',
 235: 'PEPPERS, CHILE - YIELD, MEASURED IN CWT / ACRE',
 302: 'SWEET POTATOES - PRODUCTION, MEASURED IN CWT',
 303: 'SWEET POTATOES - YIELD, MEASURED IN CWT / ACRE',
 242: 'POTATOES - PRODUCTION, MEASURED IN CWT',
 243: 'POTATOES - YIELD, MEASURED IN CWT / ACRE',
 307: 'TOMATOES, IN THE OPEN, PROCESSING - PRODUCTION, MEASURED IN TONS',
 300: 'SWEET CORN, PROCESSING - PRODUCTION, MEASURED IN TONS',
 301: 'SWEET CORN, PROCESSING - YIELD, MEASURED IN TONS / ACRE',
 228: 'PEAS, GREEN, PROCESSING - PRODUCTION, MEASURED IN TONS',
 229: 'PEAS, GREEN, PROCESSING - YIELD, MEASURED IN TONS / ACRE',
 8: 'APPLES - PRODUCTION, MEASURED IN LB',
 222: 'PEACHES 

In [222]:
a = county_dict[X_test[2][0]]

In [223]:
a

'INDIANA'

In [226]:
a, b = county_dict[X_test[2][0]], item_dict[X_test[2][1]]

In [227]:
a, b

('INDIANA', 'APPLES - YIELD, MEASURED IN BU / ACRE')

In [238]:
yhat[6]

11643169.0

In [237]:
y_test[6]

array([19815000.])